clientInfoSecret:
  create: true
  name: synology-client-info
controller:
  affinity: {}
  nodeSelector: {}
  tolerations: []
fullnameOverride: ""
installCSIDriver: true
nameOverride: ""
node:
  affinity: {}
  nodeSelector: {}
  tolerations: []
snapshotter:
  affinity: {}
  nodeSelector: {}
  tolerations: []
storageClasses:
  synology-csi-retain:
    isDefault: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    parameters:
      dsm: "synology.polaris"
      type: thin
      fsType: btrfs
      location: /volume2
  synology-csi-delete:
    isDefault: true
    reclaimPolicy: Delete
    parameters:
      dsm: "synology.polaris"
      type: thin
      fsType: btrfs
      location: /volume2
volumeSnapshotClasses:
  synology-csi-retain:
    deletionPolicy: Retain
    parameters:
      description: "Kubernetes CSI"
  synology-csi-delete:
    deletionPolicy: Delete
    parameters:
      description: "Kubernetes CSI"
