---
clientInfoSecret:
  create: false
  name: "synology-client-info"
# Specifies affinity, nodeSelector and tolerations for the controller StatefulSet
controller:
  affinity: {}
  nodeSelector: {}
  tolerations: []
fullnameOverride: ""
images:
  attacher:
    image: registry.k8s.io/sig-storage/csi-attacher
    pullPolicy: IfNotPresent
    tag: v4.2.0
  nodeDriverRegistrar:
    image: registry.k8s.io/sig-storage/csi-node-driver-registrar
    pullPolicy: IfNotPresent
    tag: v2.6.3
  plugin:
    image: ghcr.io/zebernst/synology-csi
    pullPolicy: IfNotPresent
    # Defaults to {{ $.Chart.AppVersion }} if empty or not present:
    tag: ""
  provisioner:
    image: registry.k8s.io/sig-storage/csi-provisioner
    pullPolicy: IfNotPresent
    tag: v3.4.0
  resizer:
    image: registry.k8s.io/sig-storage/csi-resizer
    pullPolicy: IfNotPresent
    tag: v1.7.0
  snapshotter:
    image: registry.k8s.io/sig-storage/csi-snapshotter
    pullPolicy: IfNotPresent
    tag: v4.2.1
installCSIDriver: true
nameOverride: ""
node:
  affinity: {}
  nodeSelector: {}
  tolerations: []
snapshotter:
  affinity: {}
  nodeSelector: {}
  tolerations: []
storageClasses:
  retain:
    isDefault: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    parameters:
      dsm: "synology.polaris"
      fsType: btrfs
      location: /volume2
  delete:
    isDefault: true
    reclaimPolicy: Delete
    parameters:
      dsm: "synology.polaris"
      fsType: btrfs
      location: /volume2
volumeSnapshotClasses:
  retain:
    deletionPolicy: Retain
    parameters:
      description: "Kubernetes CSI"
  delete:
    deletionPolicy: Delete
    parameters:
      description: "Kubernetes CSI"
