apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: client-info-secret
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yml: AgAOUKm9waRX2TAFEm6zOcB3fDERSUomx6qbRhoA0RPzZxDSeLNU6E382unvl8C+u3S1Q7IXTuXwOWB51aZb/Dy46BZFdQCoIZTrFmm5dgMNhS7hSvoDxSK+ua9l2fDDUzCb3/TsKI1sevSYst/XcUTo+9XPjUgDW+c1gx4bz47Z1A28LLzLYJZrtPD2al2DhH2FI3QvbrFlkGuQeByBPSjXfkooioDm804adHTkR0UzQgNiayDP+CY7XOT35GNJqGFOpFMXm0IllcDng7xrKcyRUIA7u+MbbrTqZmXJndrUa4UqgMv1Hma2fx386jj9liB6zfwKMKJ8JnxC8F3mgd2UZ+8vpiXZ1VQqP3w7YlnnXuWvRItPXcvnB0GA4eO5SsF0gd/cEMP4z6L6JL7yPw5lAMx0DqZt8nnSMsfCEdiS06W//eQquo2YEIYLiG0/1BpU/GSI+H7IzC9H7UfcabV+Y8oMwCbLI0x3BLgu0+hRKMvI+juL56WAiRBPpxLG51djtAkWIJFAtpN7Ex9ffOWl1D1j1XDql3G/ZaM7Oqpm5V6R8THAOwIpMRkPDYIeMDJ/03Dw0CfYvIY8/eCnEQ00c+Hr3jBg2OvVMJEYE0Dlsl0GGQ8vfvrSyMlR32UsfZH+PeeJO+td3suvUwGtB56MI9mZNvdrgrEzoL3qtbj1P2xr5GrpEq3ORbUQ9hzl7Dc7IKEotWTM1yk4EvpO4ZvK81ZVGRf7kxYVB3ijkescMyWStfQVMB0TxywyVlUdJfFrQZ3+EoTHW66UM6Ki+3PlEbDABqKz2TovFPxeLSDejCkI6gg2V+Qsy0EwY8uso35ibEJ5C0nGLxaYytrfONkdShOXSIUb6gmgN6k=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: client-info-secret
      namespace: synology-csi

